on: [push]

jobs:
  ocl_validation:
    runs-on: ubuntu-latest
    name: OCL Validation
    steps:
      - uses: actions/checkout@v2
      - name: OCL Validation Action
        uses: gdaniel/ocl-validation-action@v2
        with:
          metamodel: 'model/graph.ecore'
          model: 'model/graph-example.xmi'
          constraints: 'constraints/constraints.ocl'